[theme]
# Primary accent color for interactive elements.
primaryColor = "#FFA500"  # Darker orange

# Background color for the main content area.
backgroundColor = "#36454f"  # Keep as is

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#455a64"  # Darker slate gray for contrast

# Color used for almost all text.
textColor = "#fff"  # Keep as is

# Optional accent color for links/highlights.
accentColor = "#4FC3F7"  # Light blue
